import os
import json
import logging
import datetime
import math
import re

# Import helper checks from AI rules
from ai_rules import check_content_safety, get_ai_priority_rating, get_non_programming_priority_rating, OpenRouter429Error
from config import OPENROUTER_API_KEY

# --- Load Config ---
CONFIG_PATH = os.path.join(os.path.dirname(__file__), "config.json")
with open(CONFIG_PATH, "r", encoding="utf-8") as f:
    config = json.load(f)

THRESHOLDS = config["THRESHOLDS"]
LANGUAGE_PROFILES = config["LANGUAGE_PROFILES"]
NON_PROGRAMMING_LANGS = set(config["NON_PROGRAMMING_LANGS"])

# Compile SPAM_REGEX_BLACKLIST
SPAM_REGEX_BLACKLIST = [
    re.compile(pattern, re.IGNORECASE) for pattern in config["SPAM_REGEX_BLACKLIST"]
]

# Compile PII_REGEX_PATTERNS
PII_REGEX_PATTERNS = [
    re.compile(pattern) for pattern in config["PII_REGEX_PATTERNS"]
]


# --- LOCAL PATTERN PRE-CHECKS ---

def has_pii(content: str) -> bool:
    """Checks if the content contains PII or sensitive keys."""
    return any(pattern.search(content) for pattern in PII_REGEX_PATTERNS)


def has_spam_patterns(content: str) -> bool:
    """Checks if the content matches any known spam pattern from the blacklist."""
    return any(pattern.search(content) for pattern in SPAM_REGEX_BLACKLIST)


# --- HELPER FUNCTIONS ---

def get_base_priority(language: str) -> float:
    """Gets the base score for the language."""
    profile = LANGUAGE_PROFILES.get(language.lower(), LANGUAGE_PROFILES["default"])
    return profile["base_score"]


def calculate_age_decay(created_at: datetime.datetime, language: str) -> float:
    """Calculates age score based on decay rate."""
    profile = LANGUAGE_PROFILES.get(language.lower(), LANGUAGE_PROFILES["default"])
    decay_days = profile["decay_days"]

    # Ensure created_at is timezone-aware
    if created_at.tzinfo is None:
        created_at = created_at.replace(tzinfo=datetime.timezone.utc)

    now = datetime.datetime.now(datetime.timezone.utc)
    age_days = (now - created_at).days

    if age_days < 0:
        return 1.0  # Future date, max score

    # Linear decay. Snippet older than decay_days will have score 0.2 (min)
    decay_score = 1.0 - (age_days / decay_days)

    # Set minimum threshold (e.g. 0.2)
    return max(0.2, decay_score)


# --- ORIGINAL RULE-BASED SCORING FALLBACK ---

def calculate_priority_rule_based(content: str, language: str, created_at: datetime.datetime) -> tuple[float, str]:
    """Original robust rule-based priority score calculation. Used as a safe fallback."""
    lang = language.lower() if language else "plaintext"

    lang_base_score = get_base_priority(lang)
    content_length = len(content)

    # 1. Length Score
    optimal_length = THRESHOLDS["optimal_length"]
    if content_length <= optimal_length:
        length_score = content_length / optimal_length
    else:
        # Apply decay function for snippets that are too long
        # Formula: score = 0.2 + 0.8 * e^(-(length_ratio - 1)^2 / 4)
        # Starts decreasing from 1.0 and asymptotes to 0.2
        length_ratio = content_length / optimal_length
        decay_factor = math.exp(-((length_ratio - 1) ** 2) / 4)
        length_score = 0.2 + 0.8 * decay_factor

    length_score = max(0.2, min(1.0, length_score))  # Ensure score is within [0.2, 1.0]

    # 2. Age Decay Score
    age_score = calculate_age_decay(created_at, lang)

    # 3. Neutral defaults for syntax and utility scores (Pygments tokens analysis removed)
    syntax_score = 0.5
    utility_score = 0.5

    # --- PHASE 3: FINAL CALCULATION ---
    lang_profile = LANGUAGE_PROFILES.get(lang, LANGUAGE_PROFILES["default"])
    weights = lang_profile["scoring_weights"]

    raw_score = (
        weights["length"] * length_score +
        weights["syntax"] * syntax_score +
        weights["utility"] * utility_score +
        weights["age"] * age_score
    )

    final_priority = lang_base_score + (1.0 - lang_base_score) * raw_score

    # Ensure the score is within the valid range [0.1, 1.0]
    final_priority = max(0.1, min(1.0, final_priority))

    assessment_details = (
        f"Length:{length_score:.2f} (w:{weights['length']}), "
        f"Syntax:{syntax_score:.2f} (w:{weights['syntax']}) [Fallback], "
        f"Utility:{utility_score:.2f} (w:{weights['utility']}) [Fallback], "
        f"Age:{age_score:.2f} (w:{weights['age']})"
    )
    assessment_string = f"Priority={final_priority:.3f} | Details: {assessment_details}"

    return final_priority, assessment_string


# --- LOCK FILE & DEFAULT CONFIG DETECTION ---

def is_lock_file_or_default_config(content: str, lang: str) -> bool:
    """Detects common lock files or minimal/default framework configuration files."""
    content_lower = content.lower()

    # 1. Lock file detection
    # Cargo.lock or poetry.lock
    if "automatically @generated by cargo" in content_lower:
        return True
    if "poetry.lock" in content_lower or "generated by poetry" in content_lower:
        return True
    if "[[package]]" in content and "name =" in content_lower and "version =" in content_lower and lang == "toml":
        return True

    # package-lock.json
    if "lockfileversion" in content_lower and lang == "json":
        return True

    # yarn.lock
    if "yarn lockfile v1" in content_lower or "__metadata:" in content_lower:
        return True

    # pnpm-lock.yaml / pnpm-lock.yml
    if "lockfileversion:" in content_lower and ("importers:" in content_lower or "packages:" in content_lower):
        return True

    # Composer lock
    if "composer-cli" in content_lower or ("content-hash" in content_lower and lang == "json"):
        return True

    # 2. Check for default/empty framework config files
    stripped = "".join(content.split())
    if lang == "json":
        if stripped in ["{}", '{"compileroptions":{}}', '{"presets":[]}']:
            return True
    if lang in ["yaml", "yml"]:
        if stripped in ["", "{}"]:
            return True

    return False


# --- MAIN CALCULATION ENTRYPOINT ---

def calculate_priority(content: str, language: str, created_at: datetime.datetime, is_verified: bool = False) -> tuple[float, str, str | None]:
    """Calculates the final priority score (0.1 to 1.0) using hybrid priority logic (Regex -> AI).

    Returns: (priority_score, assessment_string, ai_status)
    """
    logging.debug(f"calculate_priority input -> lang: {language}, len: {len(content) if content is not None else 0}, is_verified: {is_verified}")

    # 1. Admin Verification Overrides
    if is_verified:
        return 1.0, "Assessment: Overridden by Admin Manual Verification.", None

    lang = language.lower() if language else "plaintext"

    # 2. Too Short check (< 15 characters)
    stripped_content = content.strip() if content else ""
    if len(stripped_content) < 15:
        logging.debug("Rejected: Content too short")
        return 0.1, "Assessment: Rejected (Too short - less than 15 characters).", None

    # 3. Too Long check (1000+ lines)
    if len(content.splitlines()) >= 1000:
        logging.debug("Rejected: Too long (1000+ lines)")
        return 0.1, "Assessment: Rejected (Too long - 1000+ lines).", None

    # 4. Too Long check (50000+ characters)
    if len(content) >= 50000:
        logging.debug("Rejected: Too long (50000+ characters)")
        return 0.1, "Assessment: Rejected (Too long - 50000+ characters).", None

    # 5. Lock files & default configs check
    if is_lock_file_or_default_config(content, lang):
        logging.debug("Rejected: Lock file or default framework configuration file")
        return 0.1, "Assessment: Rejected (Lock file or default framework configuration file).", None

    # 6. Likely spam checks (Reusing spam regex checking helper)
    if has_spam_patterns(content):
        logging.debug("Rejected: Spam detected")
        return 0.1, "Assessment: Rejected (Spam detected).", None

    # 7. Sensitive public UGC / PII checks
    # Local pattern pre-check
    if has_pii(content):
        logging.debug("Rejected: Sensitive information/PII detected via local checks")
        return 0.1, "Assessment: Rejected (Sensitive information detected via local checks).", None

    # From here, we are doing AI Routing!
    try:
        # External Nemotron safety check
        openrouter_key = OPENROUTER_API_KEY
        if openrouter_key:
            is_safe, safety_assessment = check_content_safety(content, openrouter_key)
            if not is_safe:
                logging.debug("Rejected: Content safety check failed (Nemotron)")
                return 0.1, safety_assessment, "completed"

        # 8. Check if non-programming language to evaluate with inclusionai/ling-3.0-tiny:free
        routing_is_non_programming = lang in NON_PROGRAMMING_LANGS
        logging.debug(f"Routing to AI rating. Is non-programming: {routing_is_non_programming}")

        if routing_is_non_programming:
            if openrouter_key:
                ai_score, ai_assessment = get_non_programming_priority_rating(content, lang, openrouter_key)
                if ai_score is not None:
                    return ai_score, ai_assessment, "completed"
            # Fallback to Rule-based calculation if AI is disabled or fails
            logging.info("Falling back to robust rule-based priority calculation for non-programming language.")
            fallback_score, fallback_assessment = calculate_priority_rule_based(content, lang, created_at)
            return fallback_score, fallback_assessment, None

        # 9. Main LLM Priority Rating with cohere/north-mini-code:free for programming languages
        if openrouter_key:
            ai_score, ai_assessment = get_ai_priority_rating(content, lang, openrouter_key)
            if ai_score is not None:
                return ai_score, ai_assessment, "completed"

        # Fallback to Rule-based calculation if AI is disabled or fails
        logging.info("Falling back to robust rule-based priority calculation.")
        fallback_score, fallback_assessment = calculate_priority_rule_based(content, lang, created_at)
        return fallback_score, fallback_assessment, None

    except OpenRouter429Error as e:
        logging.warning(f"AI routing encountered 429 error: {e}. Bypassing with pending status.")
        fallback_score, fallback_assessment = calculate_priority_rule_based(content, lang, created_at)
        return fallback_score, fallback_assessment, "pending"

